### ISSUE TITLE
questions about the label

### ISSUE THREAD

**Issue by ljw919** [DevendraSinghChundawat1/Medical-Image-Segmentation-using-DDPM-and-MONAI#1]
I want to know that, is your your label mask only contains 0 or 1 ? like a one-hot encode ? And can we integrate crossentropy loss into the model ?

**Comment by ljw919** [comment]
> I want to know that, is your your label mask only contains 0 or 1 ? like a one-hot encode ? And can we integrate crossentropy loss into the model ?

so that through the reverse diffusion process, we can get a probability mask (values 0-1), then we can use the torch.argmax to get the label ?

**Comment by DevendraSinghChundawat1** [comment]
yes label mask only contains 0 and 1.
