### ISSUE TITLE
Diffusioninferer

### ISSUE THREAD

**Issue by nightandweather** [DevendraSinghChundawat1/Medical-Image-Segmentation-using-DDPM-and-MONAI#2]
Hello, Thank you for sharing your code!

I'm executing the code, but prompt says the diffusioninfer is not defined.

https://github.com/DevendraSinghChundawat1/Brain-Tumor-Segmentation-using-DDPM/blob/d19885c5978803446dfab5641ae7d52438dd4db7/segmentation_with_ddpm.py#LL127C18-L127C18

**Comment by DevendraSinghChundawat1** [comment]
Sorry, that line is not required. I will remove it but for now, you can remove it.
